displayName=Slayer Loot
author=Papa Bald
description=Tracks loot, kills, and actual profit per Slayer task
tags=slayer,loot,tracker,profit,kills
plugins=com.papabald.slayerloot.SlayerLootPlugin
version=1.0.0
build=standard
